package WordyApp;

/**
* WordyApp/WordyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class WordyHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.Wordy value = null;

  public WordyHolder ()
  {
  }

  public WordyHolder (WordyApp.Wordy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyHelper.type ();
  }

}
