package WordyApp;


/**
* WordyApp/WordyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public interface WordyOperations 
{
  void login (String username, String password) throws WordyApp.WordyPackage.WrongPasswordOrUsernameException, WordyApp.WordyPackage.AccountDoesNotExistException, WordyApp.WordyPackage.AccountIsLoggedInException;

  // not be found in the database
  void logout (String username);

  // logs out the client.
  int create_or_join_lobby (String username);

  // meet the requirement to start. The timer will be implemented in the client side.
  void can_start (int lobbyNumber) throws WordyApp.WordyPackage.CriteriaNotMetException;

  // timer in the createOrJoinLobby has ended.
  void verify_guess (String word, String username, int lobbyID) throws WordyApp.WordyPackage.InvalidWordException, WordyApp.WordyPackage.WordTooShortException;

  // even if there are multiple players who sent it.
  int get_score (String username, int lobbyID);

  // assign score to a player every end of round.
  String get_letters (int lobbyID);

  // get letters from the server.
  void reassign_letters (int lobbyID, String username);

  // reassign the letters in a lobby
  void stop_timer (int lobbyID);

  // stop or start timer
  void start_timer (int lobbyID);

  // starts the timer only if the user is the host of the lobby
  void update_round (int stat, int lobbyID);

  // updates the status of the round, whether a new round has started or not.
  boolean get_round_stat (int lobbyID);

  // gets the round status of a lobby
  boolean is_host (String username, int lobbyID);

  // determines whether the player is the host of a lobby.
  void remove_lobby (int lobbyID);

  // removes lobby when it is empty.
  void remove_player_on_quit (int lobbyID);

  // removes a player on the record when they quit the game.
  String leaderboards () throws WordyApp.WordyPackage.EmptyListException;

  // is empty or no record exists yet.
  String lengthiest () throws WordyApp.WordyPackage.EmptyListException;
} // interface WordyOperations
