package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/AccountIsLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class AccountIsLoggedInException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public AccountIsLoggedInException ()
  {
    super(AccountIsLoggedInExceptionHelper.id());
  } // ctor

  public AccountIsLoggedInException (String _msg)
  {
    super(AccountIsLoggedInExceptionHelper.id());
    msg = _msg;
  } // ctor


  public AccountIsLoggedInException (String $reason, String _msg)
  {
    super(AccountIsLoggedInExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class AccountIsLoggedInException
