package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/AccountDoesNotExistExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class AccountDoesNotExistExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.AccountDoesNotExistException value = null;

  public AccountDoesNotExistExceptionHolder ()
  {
  }

  public AccountDoesNotExistExceptionHolder (WordyApp.WordyPackage.AccountDoesNotExistException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.AccountDoesNotExistExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.AccountDoesNotExistExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.AccountDoesNotExistExceptionHelper.type ();
  }

}
