package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/AccountDoesNotExistException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class AccountDoesNotExistException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public AccountDoesNotExistException ()
  {
    super(AccountDoesNotExistExceptionHelper.id());
  } // ctor

  public AccountDoesNotExistException (String _msg)
  {
    super(AccountDoesNotExistExceptionHelper.id());
    msg = _msg;
  } // ctor


  public AccountDoesNotExistException (String $reason, String _msg)
  {
    super(AccountDoesNotExistExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class AccountDoesNotExistException
