package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/AccountIsLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class AccountIsLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.AccountIsLoggedInException value = null;

  public AccountIsLoggedInExceptionHolder ()
  {
  }

  public AccountIsLoggedInExceptionHolder (WordyApp.WordyPackage.AccountIsLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.AccountIsLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.AccountIsLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.AccountIsLoggedInExceptionHelper.type ();
  }

}
