package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/CriteriaNotMetExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class CriteriaNotMetExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.CriteriaNotMetException value = null;

  public CriteriaNotMetExceptionHolder ()
  {
  }

  public CriteriaNotMetExceptionHolder (WordyApp.WordyPackage.CriteriaNotMetException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.CriteriaNotMetExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.CriteriaNotMetExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.CriteriaNotMetExceptionHelper.type ();
  }

}
