package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/CriteriaNotMetException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class CriteriaNotMetException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public CriteriaNotMetException ()
  {
    super(CriteriaNotMetExceptionHelper.id());
  } // ctor

  public CriteriaNotMetException (String _msg)
  {
    super(CriteriaNotMetExceptionHelper.id());
    msg = _msg;
  } // ctor


  public CriteriaNotMetException (String $reason, String _msg)
  {
    super(CriteriaNotMetExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class CriteriaNotMetException
