package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/EmptyListException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class EmptyListException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public EmptyListException ()
  {
    super(EmptyListExceptionHelper.id());
  } // ctor

  public EmptyListException (String _msg)
  {
    super(EmptyListExceptionHelper.id());
    msg = _msg;
  } // ctor


  public EmptyListException (String $reason, String _msg)
  {
    super(EmptyListExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class EmptyListException
