package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/EmptyListExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class EmptyListExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.EmptyListException value = null;

  public EmptyListExceptionHolder ()
  {
  }

  public EmptyListExceptionHolder (WordyApp.WordyPackage.EmptyListException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.EmptyListExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.EmptyListExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.EmptyListExceptionHelper.type ();
  }

}
