package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/InvalidWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class InvalidWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.InvalidWordException value = null;

  public InvalidWordExceptionHolder ()
  {
  }

  public InvalidWordExceptionHolder (WordyApp.WordyPackage.InvalidWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.InvalidWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.InvalidWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.InvalidWordExceptionHelper.type ();
  }

}
