package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/InvalidWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class InvalidWordException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public InvalidWordException ()
  {
    super(InvalidWordExceptionHelper.id());
  } // ctor

  public InvalidWordException (String _msg)
  {
    super(InvalidWordExceptionHelper.id());
    msg = _msg;
  } // ctor


  public InvalidWordException (String $reason, String _msg)
  {
    super(InvalidWordExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class InvalidWordException
