package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/LeaderboardsMap.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class LeaderboardsMap implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public LeaderboardsMap ()
  {
  } // ctor

  public LeaderboardsMap (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class LeaderboardsMap
