package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/LeaderboardsMapHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class LeaderboardsMapHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.LeaderboardsMap value = null;

  public LeaderboardsMapHolder ()
  {
  }

  public LeaderboardsMapHolder (WordyApp.WordyPackage.LeaderboardsMap initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.LeaderboardsMapHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.LeaderboardsMapHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.LeaderboardsMapHelper.type ();
  }

}
