package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/LengthiestMap.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class LengthiestMap implements org.omg.CORBA.portable.IDLEntity
{
  public String word = null;
  public String username = null;

  public LengthiestMap ()
  {
  } // ctor

  public LengthiestMap (String _word, String _username)
  {
    word = _word;
    username = _username;
  } // ctor

} // class LengthiestMap
