package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/WordTooShortException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class WordTooShortException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public WordTooShortException ()
  {
    super(WordTooShortExceptionHelper.id());
  } // ctor

  public WordTooShortException (String _msg)
  {
    super(WordTooShortExceptionHelper.id());
    msg = _msg;
  } // ctor


  public WordTooShortException (String $reason, String _msg)
  {
    super(WordTooShortExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class WordTooShortException
