package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/WordNotInAcceptedListException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class WordNotInAcceptedListException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public WordNotInAcceptedListException ()
  {
    super(WordNotInAcceptedListExceptionHelper.id());
  } // ctor

  public WordNotInAcceptedListException (String _msg)
  {
    super(WordNotInAcceptedListExceptionHelper.id());
    msg = _msg;
  } // ctor


  public WordNotInAcceptedListException (String $reason, String _msg)
  {
    super(WordNotInAcceptedListExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class WordNotInAcceptedListException
