package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/WordTooShortExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class WordTooShortExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.WordTooShortException value = null;

  public WordTooShortExceptionHolder ()
  {
  }

  public WordTooShortExceptionHolder (WordyApp.WordyPackage.WordTooShortException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.WordTooShortExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.WordTooShortExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.WordTooShortExceptionHelper.type ();
  }

}
