package WordyApp.WordyPackage;

/**
* WordyApp/WordyPackage/WordNotInAcceptedListExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class WordNotInAcceptedListExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public WordyApp.WordyPackage.WordNotInAcceptedListException value = null;

  public WordNotInAcceptedListExceptionHolder ()
  {
  }

  public WordNotInAcceptedListExceptionHolder (WordyApp.WordyPackage.WordNotInAcceptedListException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WordyApp.WordyPackage.WordNotInAcceptedListExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WordyApp.WordyPackage.WordNotInAcceptedListExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WordyApp.WordyPackage.WordNotInAcceptedListExceptionHelper.type ();
  }

}
