package WordyApp.WordyPackage;


/**
* WordyApp/WordyPackage/WrongPasswordOrUsernameException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, June 23, 2023 10:47:18 AM CST
*/

public final class WrongPasswordOrUsernameException extends org.omg.CORBA.UserException
{
  public String msg = null;

  public WrongPasswordOrUsernameException ()
  {
    super(WrongPasswordOrUsernameExceptionHelper.id());
  } // ctor

  public WrongPasswordOrUsernameException (String _msg)
  {
    super(WrongPasswordOrUsernameExceptionHelper.id());
    msg = _msg;
  } // ctor


  public WrongPasswordOrUsernameException (String $reason, String _msg)
  {
    super(WrongPasswordOrUsernameExceptionHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class WrongPasswordOrUsernameException
